package org.sonar.skyscanner.java.regex;

public interface UserIds {
    String[] patterns = {
            ".*clientConfig.setProxyUsername\\(\"([^\"]*)\".*",
            ".*clientConfig.setProxyUsername\\('([^']*)'.*",
            ".*USERNAME\\s*=\\s*(\\S*).*",
            ".*USERNAME\\s*=>\\s*(\\S*).*",
            ".*id\\s*=\\s*([^;]*);.*",
            ".*id\\s*=\\s*(\\S*).*",
            ".*ID\\s*=\\s*(\\S*).*",
            ".*id\\s*:\\s*(\\S*).*",
            ".*ID\\s*=\\s*(\\S*).*",
            ".*-\\s*username\\s*(\\S*).*",
            ".*user-name\\s*(\\S*).*",
            ".*cloud\\.aws\\.cof\\.user\\.eid=(\\S*).*",
            ".*username>(\\S*).*",
            ".*user[N|n]ame\"\\s*=>\\s*\"([^\"]*)\".*",
            ".*user[N|n]ame'\\s*=>\\s*'([^']*)'.*",
            ".*[U|u]sername\":\\s*(\\S*).*",
            ".*[U|u]sername':\\s*(\\S*).*",
            ".*user\"\\s*=>(\\S*).*",
            ".*user'\\s*=>(\\S*).*",
            ".*user\"\\s*:\\s*(\\S*).*",
            ".*user'\\s*:\\s*(\\S*).*",
            ".*adminName=cn\\\\?=([^,]*),.*",
            ".*username$",
            ".*username\\s*:\\s*(\\S*).*",
            ".*AuthLDAPBindDN\\s*r\"CN=([^,]*).*",
            ".*AuthLDAPBindDN\\s*r'CN=([^,]*).*",
            ".*LDAPLOGIN=([^\\s@]*)@",
            ".*user\\s*=\\s*(\\S*).*2",
            ".*user\\s*:\\s*(\\S*).*",
            ".*user.name\\s*=\\s*(\\S*).*",
            ".*USER\\s*=\\s*(\\S*).*",
            ".*user\\s*=>\\s*(\\S*).*",
            ".*username\\s*=\\s*(\\S*).*",
            ".*username\\s*=\\s*([^&]*)&.*",
            ".*username\">([^<]*)<.*",
            ".*username'>([^<]*)<.*",
            ".*USR\\s*=\\s*(\\S*).*",
            ".*dn\\s*:\\s*(\\S*).*",
            ".*USERID\\s*=\\s*(\\S*).*",
            ".*USER_NAME\\s*=\\s*(\\S*).*",
            ".*username;//=\"(\\S*)\".*",
            ".*//=\"(\\S*)\".*\n"
    };
}
